name: Deploy GeoHealth

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Angular
        run: |
          cd frontend
          npm install
          npm run build -- --configuration production


      - name: Build Spring Boot JAR
        run: |
          cd backend
          ./mvnw package -DskipTests

      - name: Copy Angular files to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "frontend/dist/GeoHealth_Angular/browser/"
          target: "/opt/geohealth/frontend"
          strip_components: 3

      - name: Copy JAR to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "backend/target/*.jar"
          target: "/opt/geohealth/backend"
          strip_components: 2

      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "docker-compose.yml"
          target: "/opt/geohealth"

      - name: Restart services on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /opt/geohealth
            docker compose --env-file .env up -d
            pkill -f geohealth || true
            sleep 2
            nohup java -jar backend/*.jar \
              --spring.profiles.active=prod \
              $(cat .env | xargs) \
              > /opt/geohealth/app.log 2>&1 &